### ISSUE TITLE
Getting the time/clock of CDJ

### ISSUE THREAD

**Issue by jellohouse** [EvanPurkhiser/prolink-connect#20]
Hey!

First I wanted to say amazing work you did with this library @evanpurkhiser ! :)

I'm working on a little project and am trying to use it, however I don't have a CDJ at hand at the moment, so it's a bit hard for me to test.

I'm trying to get the current time of a CDJ.
I was wondering, is there an event emitted as the time/clock of a CDJ is playing?
If not, do you have any idea on how I could get the current time?

Thanks in advance!

**Comment by evanpurkhiser** [comment]
Hey there!

Unfortunately you cannot get an accurate clock. You may want to checkout something like [Beat Link Trigger](https://github.com/Deep-Symmetry/beat-link-trigger) which supports interpolation of exact timings. There is a java library https://github.com/Deep-Symmetry/beat-link
