### ISSUE TITLE
What is meant by effectivePitch and sliderPitch?

### ISSUE THREAD

**Issue by jellohouse** [EvanPurkhiser/prolink-connect#21]
Firstly what do the effectivePitch and sliderPitch represent in the CDJstatus?

Are they supposed to be the tempo (bpm) slider? 
Because the word pitch is a bit confusing it sounds like we are talking about the pitch (key) of the song... or is that what it means?

And secondly what is the difference between the effectivePitch and sliderPitch?

**Comment by evanpurkhiser** [comment]
They represent pitch change (or yes, tempo change) as a percentage value.

Here's the documentation on `effectivePitch` and `sliderPitch` https://github.com/evanpurkhiser/prolink-connect/blob/main/src/status/types.ts#L87-L96

They are labeled pitch for historical reasons https://en.wikipedia.org/wiki/Pitch_control
